//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Data.FullDomain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Mendeo.Mercurius.Model.FullDomain;
    using Attribute = Mendeo.Mercurius.Model.FullDomain.Attribute;
    
    public partial class MercuriusEntities : DbContext
    {
        public MercuriusEntities()
            : base("name=MercuriusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AbuseProductReviewMap> AbuseProductReviewMap { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AddressType> AddressType { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Attribute> Attribute { get; set; }
        public virtual DbSet<AttributeBehavior> AttributeBehavior { get; set; }
        public virtual DbSet<AttributeCategoryMap> AttributeCategoryMap { get; set; }
        public virtual DbSet<AttributeEvent> AttributeEvent { get; set; }
        public virtual DbSet<AttributeItem> AttributeItem { get; set; }
        public virtual DbSet<AttributeType> AttributeType { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryCultureMap> CategoryCultureMap { get; set; }
        public virtual DbSet<CategoryImageMap> CategoryImageMap { get; set; }
        public virtual DbSet<CategoryProductMap> CategoryProductMap { get; set; }
        public virtual DbSet<Continent> Continent { get; set; }
        public virtual DbSet<Culture> Culture { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<EncryptionType> EncryptionType { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<ImageType> ImageType { get; set; }
        public virtual DbSet<MailerTemplate> MailerTemplate { get; set; }
        public virtual DbSet<MailerTemplateType> MailerTemplateType { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<PageBehavior> PageBehavior { get; set; }
        public virtual DbSet<PageCultureMap> PageCultureMap { get; set; }
        public virtual DbSet<PageEvent> PageEvent { get; set; }
        public virtual DbSet<PageType> PageType { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Phone> Phone { get; set; }
        public virtual DbSet<PhoneType> PhoneType { get; set; }
        public virtual DbSet<PrintTemplate> PrintTemplate { get; set; }
        public virtual DbSet<PrintTemplateType> PrintTemplateType { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductAnnounceType> ProductAnnounceType { get; set; }
        public virtual DbSet<ProductAnnounceTypeCultureMap> ProductAnnounceTypeCultureMap { get; set; }
        public virtual DbSet<ProductAttributeMap> ProductAttributeMap { get; set; }
        public virtual DbSet<ProductBehavior> ProductBehavior { get; set; }
        public virtual DbSet<ProductCultureMap> ProductCultureMap { get; set; }
        public virtual DbSet<ProductEvent> ProductEvent { get; set; }
        public virtual DbSet<ProductFavorite> ProductFavorite { get; set; }
        public virtual DbSet<ProductImageMap> ProductImageMap { get; set; }
        public virtual DbSet<ProductImageType> ProductImageType { get; set; }
        public virtual DbSet<ProductReview> ProductReview { get; set; }
        public virtual DbSet<ProductStatus> ProductStatus { get; set; }
        public virtual DbSet<ProductStatusInternalComment> ProductStatusInternalComment { get; set; }
        public virtual DbSet<ProductStatusInternalCommentMap> ProductStatusInternalCommentMap { get; set; }
        public virtual DbSet<ProductStatusReason> ProductStatusReason { get; set; }
        public virtual DbSet<ProductStatusReasonCategory> ProductStatusReasonCategory { get; set; }
        public virtual DbSet<ProductStatusReasonCategoryCultureMap> ProductStatusReasonCategoryCultureMap { get; set; }
        public virtual DbSet<ProductStatusReasonCultureMap> ProductStatusReasonCultureMap { get; set; }
        public virtual DbSet<ProductStatusReasonEntry> ProductStatusReasonEntry { get; set; }
        public virtual DbSet<ProductStatusReasonEntryMap> ProductStatusReasonEntryMap { get; set; }
        public virtual DbSet<ProductStatusReasonLink> ProductStatusReasonLink { get; set; }
        public virtual DbSet<ProductStatusType> ProductStatusType { get; set; }
        public virtual DbSet<ProductStatusTypeCultureMap> ProductStatusTypeCultureMap { get; set; }
        public virtual DbSet<RolePermission> RolePermission { get; set; }
        public virtual DbSet<RolePermissionMap> RolePermissionMap { get; set; }
        public virtual DbSet<SellerType> SellerType { get; set; }
        public virtual DbSet<SellerTypeCultureMap> SellerTypeCultureMap { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserReview> UserReview { get; set; }
        public virtual DbSet<UserReviewMap> UserReviewMap { get; set; }
        public virtual DbSet<UserReviewType> UserReviewType { get; set; }
        public virtual DbSet<UserReviewTypeCultureMap> UserReviewTypeCultureMap { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserRoleMap> UserRoleMap { get; set; }
        public virtual DbSet<WhishList> WhishList { get; set; }
        public virtual DbSet<WhishListBehavior> WhishListBehavior { get; set; }
        public virtual DbSet<WhishListEvent> WhishListEvent { get; set; }
        public virtual DbSet<WhishListProductMap> WhishListProductMap { get; set; }
        public virtual DbSet<CsvDelimiter> CsvDelimiter { get; set; }
        public virtual DbSet<CustomExport> CustomExport { get; set; }
        public virtual DbSet<SourceType> SourceType { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Continent1> Continent1 { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<PostalCode> PostalCode { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<AccountMailQueue> AccountMailQueue { get; set; }
        public virtual DbSet<ProductMailQueue> ProductMailQueue { get; set; }
        public virtual DbSet<QueueStatus> QueueStatus { get; set; }
        public virtual DbSet<GlobalSetting> GlobalSetting { get; set; }
        public virtual DbSet<GlobalSettingType> GlobalSettingType { get; set; }
        public virtual DbSet<PeopleOnline> PeopleOnline { get; set; }
        public virtual DbSet<PeopleOnlineHistory> PeopleOnlineHistory { get; set; }
        public virtual DbSet<ProductAttributeMap2> ProductAttributeMap2 { get; set; }
    }
}
