//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRL.Model.AdventureWorks
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryRegion
    {
        public CountryRegion()
        {
            this.CountryRegionCurrency = new HashSet<CountryRegionCurrency>();
            this.SalesTerritory = new HashSet<SalesTerritory>();
            this.StateProvince = new HashSet<StateProvince>();
        }
    
        public string CountryRegionCode { get; set; }
        public string Name { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<CountryRegionCurrency> CountryRegionCurrency { get; set; }
        public virtual ICollection<SalesTerritory> SalesTerritory { get; set; }
        public virtual ICollection<StateProvince> StateProvince { get; set; }
    }
}
