//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRL.Model.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserRole = new HashSet<UserRole>();
        }
    
        public System.Guid Id { get; set; }
        public string ADName { get; set; }
        public string DisplayName { get; set; }
    
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
