//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRL.Model.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSiteAccessPermission
    {
        public int Id { get; set; }
        public System.Guid RoleId { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public bool Enabled { get; set; }
        public string Comments { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
