//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbuseProductReviewMap
    {
        public int AbuseProductReviewID { get; set; }
        public int ProductReviewID { get; set; }
        public int PeopleID { get; set; }
        public bool IsAbuse { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ProductReview ProductReview { get; set; }
        public virtual User User { get; set; }
    }
}
