//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeType
    {
        public AttributeType()
        {
            this.Attribute = new HashSet<Attribute>();
            this.AttributeItem = new HashSet<AttributeItem>();
        }
    
        public int AttributeTypeID { get; set; }
        public string Name { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ItemUnitLabel { get; set; }
        public Nullable<int> ItemPrimitiveType { get; set; }
        public string NameLabel { get; set; }
    
        public virtual ICollection<Attribute> Attribute { get; set; }
        public virtual ICollection<AttributeItem> AttributeItem { get; set; }
    }
}
