//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryImageMap
    {
        public int CategoryImageID { get; set; }
        public int ImageID { get; set; }
        public int CategoryID { get; set; }
        public bool Activate { get; set; }
        public int Sort { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Image Image { get; set; }
    }
}
