//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.AttributeCategoryMap = new HashSet<AttributeCategoryMap>();
            this.CategoryCultureMap = new HashSet<CategoryCultureMap>();
            this.CategoryImageMap = new HashSet<CategoryImageMap>();
            this.CategoryProductMap = new HashSet<CategoryProductMap>();
            this.Category1 = new HashSet<Category>();
            this.Page = new HashSet<Page>();
        }
    
        public int CategoryID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool IsDefault { get; set; }
        public bool Activate { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<AttributeCategoryMap> AttributeCategoryMap { get; set; }
        public virtual ICollection<CategoryCultureMap> CategoryCultureMap { get; set; }
        public virtual ICollection<CategoryImageMap> CategoryImageMap { get; set; }
        public virtual ICollection<CategoryProductMap> CategoryProductMap { get; set; }
        public virtual ICollection<Category> Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        public virtual ICollection<Page> Page { get; set; }
    }
}
