//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Address = new HashSet<Address>();
            this.Product = new HashSet<Product>();
            this.PostalCode = new HashSet<PostalCode>();
        }
    
        public int CityID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string City1 { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Timezone { get; set; }
        public string DmaId { get; set; }
        public string CityCode { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual Country Country { get; set; }
        public virtual Region Region { get; set; }
        public virtual ICollection<PostalCode> PostalCode { get; set; }
    }
}
