//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Continent1
    {
        public Continent1()
        {
            this.Country = new HashSet<Country>();
        }
    
        public int ContinentID { get; set; }
        public Nullable<int> GeoNameID { get; set; }
        public string ContinentName { get; set; }
        public string AlternativeNames { get; set; }
        public string ISO2 { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Gtopo30 { get; set; }
    
        public virtual ICollection<Country> Country { get; set; }
    }
}
