//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CsvDelimiter
    {
        public CsvDelimiter()
        {
            this.CustomExport = new HashSet<CustomExport>();
        }
    
        public int CsvDelimiterID { get; set; }
        public string Delimiter { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CustomExport> CustomExport { get; set; }
    }
}
