//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culture
    {
        public Culture()
        {
            this.CategoryCultureMap = new HashSet<CategoryCultureMap>();
            this.MailerTemplate = new HashSet<MailerTemplate>();
            this.PageCultureMap = new HashSet<PageCultureMap>();
            this.ProductAnnounceTypeCultureMap = new HashSet<ProductAnnounceTypeCultureMap>();
            this.ProductCultureMap = new HashSet<ProductCultureMap>();
            this.ProductReview = new HashSet<ProductReview>();
            this.ProductStatusReasonCategoryCultureMap = new HashSet<ProductStatusReasonCategoryCultureMap>();
            this.ProductStatusReasonCultureMap = new HashSet<ProductStatusReasonCultureMap>();
            this.ProductStatusTypeCultureMap = new HashSet<ProductStatusTypeCultureMap>();
            this.SellerTypeCultureMap = new HashSet<SellerTypeCultureMap>();
            this.WhishList = new HashSet<WhishList>();
            this.User = new HashSet<User>();
            this.UserReview = new HashSet<UserReview>();
            this.UserReviewTypeCultureMap = new HashSet<UserReviewTypeCultureMap>();
            this.PrintTemplate = new HashSet<PrintTemplate>();
        }
    
        public int CultureID { get; set; }
        public string LanguageCode { get; set; }
        public string Locale { get; set; }
        public string DefaultCurrencyCode { get; set; }
        public string DefaultSizeCode { get; set; }
        public string DefaultWeightCode { get; set; }
        public string DefaultSizeUnit { get; set; }
        public string DefaultWeightUnit { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<CategoryCultureMap> CategoryCultureMap { get; set; }
        public virtual ICollection<MailerTemplate> MailerTemplate { get; set; }
        public virtual ICollection<PageCultureMap> PageCultureMap { get; set; }
        public virtual ICollection<ProductAnnounceTypeCultureMap> ProductAnnounceTypeCultureMap { get; set; }
        public virtual ICollection<ProductCultureMap> ProductCultureMap { get; set; }
        public virtual ICollection<ProductReview> ProductReview { get; set; }
        public virtual ICollection<ProductStatusReasonCategoryCultureMap> ProductStatusReasonCategoryCultureMap { get; set; }
        public virtual ICollection<ProductStatusReasonCultureMap> ProductStatusReasonCultureMap { get; set; }
        public virtual ICollection<ProductStatusTypeCultureMap> ProductStatusTypeCultureMap { get; set; }
        public virtual ICollection<SellerTypeCultureMap> SellerTypeCultureMap { get; set; }
        public virtual ICollection<WhishList> WhishList { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<UserReview> UserReview { get; set; }
        public virtual ICollection<UserReviewTypeCultureMap> UserReviewTypeCultureMap { get; set; }
        public virtual ICollection<PrintTemplate> PrintTemplate { get; set; }
    }
}
