//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomExport
    {
        public int CustomExportID { get; set; }
        public Nullable<int> SourceTypeID { get; set; }
        public Nullable<int> DefaultCsvDelimiter { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual CsvDelimiter CsvDelimiter { get; set; }
        public virtual SourceType SourceType { get; set; }
    }
}
