//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncryptionType
    {
        public EncryptionType()
        {
            this.User = new HashSet<User>();
        }
    
        public int EncryptionID { get; set; }
        public string EncryptionName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
}
