//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalSettingType
    {
        public GlobalSettingType()
        {
            this.GlobalSetting = new HashSet<GlobalSetting>();
        }
    
        public int GlobalSettingTypeID { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<GlobalSetting> GlobalSetting { get; set; }
    }
}
