//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.CategoryImageMap = new HashSet<CategoryImageMap>();
            this.ProductImageMap = new HashSet<ProductImageMap>();
        }
    
        public int ImageID { get; set; }
        public Nullable<int> ImageTypeID { get; set; }
        public string ThumbUrl { get; set; }
        public string FullImageUrl { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CategoryImageMap> CategoryImageMap { get; set; }
        public virtual ImageType ImageType { get; set; }
        public virtual ICollection<ProductImageMap> ProductImageMap { get; set; }
    }
}
