//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageType
    {
        public ImageType()
        {
            this.Image = new HashSet<Image>();
        }
    
        public int ImageTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Image> Image { get; set; }
    }
}
