//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailerTemplate
    {
        public MailerTemplate()
        {
            this.AccountMailQueue = new HashSet<AccountMailQueue>();
            this.ProductMailQueue = new HashSet<ProductMailQueue>();
        }
    
        public int MailerTemplateID { get; set; }
        public int MailerTypeID { get; set; }
        public int CultureID { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsHtml { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual ICollection<AccountMailQueue> AccountMailQueue { get; set; }
        public virtual MailerTemplateType MailerTemplateType { get; set; }
        public virtual ICollection<ProductMailQueue> ProductMailQueue { get; set; }
    }
}
