//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageEvent
    {
        public int PageEventID { get; set; }
        public int PageBehaviorID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int PageCultureMapID { get; set; }
        public System.DateTime EventDate { get; set; }
        public string IP { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual PageBehavior PageBehavior { get; set; }
        public virtual PageCultureMap PageCultureMap { get; set; }
        public virtual User User { get; set; }
    }
}
