//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleOnlineHistory
    {
        public int PeopleOnlineHistoryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Ip { get; set; }
        public string Browser { get; set; }
        public System.DateTime FirstActivity { get; set; }
        public Nullable<System.DateTime> EndActivity { get; set; }
        public Nullable<decimal> DurationMinute { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
