//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public People()
        {
            this.Address = new HashSet<Address>();
            this.Phone = new HashSet<Phone>();
            this.User = new HashSet<User>();
        }
    
        public int PeopleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string EMail { get; set; }
        public string Title { get; set; }
        public string Company { get; set; }
        public string LastIP { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Phone> Phone { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
