//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PhoneID { get; set; }
        public int PhoneTypeID { get; set; }
        public int PeopleID { get; set; }
        public string Phone1 { get; set; }
        public string Fax { get; set; }
        public string Cell { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual People People { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}
