//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostalCode
    {
        public PostalCode()
        {
            this.Address = new HashSet<Address>();
            this.Product = new HashSet<Product>();
        }
    
        public int PostalCodeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string PostalNumber { get; set; }
        public string PostalLabel { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Region Region { get; set; }
    }
}
