//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReview
    {
        public ProductReview()
        {
            this.AbuseProductReviewMap = new HashSet<AbuseProductReviewMap>();
        }
    
        public int ProductReviewID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string Body { get; set; }
        public bool Approved { get; set; }
        public int CultureID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int Rating { get; set; }
        public Nullable<bool> Usefull { get; set; }
        public Nullable<int> AbuseCount { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual ICollection<AbuseProductReviewMap> AbuseProductReviewMap { get; set; }
        public virtual Culture Culture { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
