//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStatus
    {
        public ProductStatus()
        {
            this.ProductStatusInternalCommentMap = new HashSet<ProductStatusInternalCommentMap>();
            this.ProductStatusReasonEntryMap = new HashSet<ProductStatusReasonEntryMap>();
        }
    
        public int ProductStatusID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductStatusTypeID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductStatusType ProductStatusType { get; set; }
        public virtual ICollection<ProductStatusInternalCommentMap> ProductStatusInternalCommentMap { get; set; }
        public virtual ICollection<ProductStatusReasonEntryMap> ProductStatusReasonEntryMap { get; set; }
    }
}
