//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImageMap
    {
        public int ProductImageID { get; set; }
        public int ProductID { get; set; }
        public int ImageID { get; set; }
        public Nullable<int> ProductImageTypeID { get; set; }
        public bool Activate { get; set; }
        public int Sort { get; set; }
        public Nullable<System.Guid> ImageIdentifier { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductImageType ProductImageType { get; set; }
    }
}
