//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CategoryProductMap = new HashSet<CategoryProductMap>();
            this.ProductAttributeMap = new HashSet<ProductAttributeMap>();
            this.ProductCultureMap = new HashSet<ProductCultureMap>();
            this.ProductFavorite = new HashSet<ProductFavorite>();
            this.ProductImageMap = new HashSet<ProductImageMap>();
            this.ProductMailQueue = new HashSet<ProductMailQueue>();
            this.ProductReview = new HashSet<ProductReview>();
            this.ProductStatus = new HashSet<ProductStatus>();
            this.UserReview = new HashSet<UserReview>();
            this.WhishListEvent = new HashSet<WhishListEvent>();
            this.WhishListProductMap = new HashSet<WhishListProductMap>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> PostalCodeID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string GoogleAddressInLine { get; set; }
        public decimal GoogleAddressLongitude { get; set; }
        public decimal GoogleAddressLatitude { get; set; }
        public string GoogleCountryCode { get; set; }
        public Nullable<int> ProductAnnounceTypeID { get; set; }
        public Nullable<int> SellerTypeID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> NumberOfImage { get; set; }
        public Nullable<int> NumberOfAttributes { get; set; }
        public Nullable<int> ProductLastStatusID { get; set; }
        public bool Activate { get; set; }
        public Nullable<int> Sort { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<CategoryProductMap> CategoryProductMap { get; set; }
        public virtual City City { get; set; }
        public virtual PostalCode PostalCode { get; set; }
        public virtual ProductAnnounceType ProductAnnounceType { get; set; }
        public virtual ProductStatusType ProductStatusType { get; set; }
        public virtual SellerType SellerType { get; set; }
        public virtual ICollection<ProductAttributeMap> ProductAttributeMap { get; set; }
        public virtual ICollection<ProductCultureMap> ProductCultureMap { get; set; }
        public virtual ICollection<ProductFavorite> ProductFavorite { get; set; }
        public virtual ICollection<ProductImageMap> ProductImageMap { get; set; }
        public virtual ICollection<ProductMailQueue> ProductMailQueue { get; set; }
        public virtual ICollection<ProductReview> ProductReview { get; set; }
        public virtual ICollection<ProductStatus> ProductStatus { get; set; }
        public virtual ICollection<UserReview> UserReview { get; set; }
        public virtual ICollection<WhishListEvent> WhishListEvent { get; set; }
        public virtual ICollection<WhishListProductMap> WhishListProductMap { get; set; }
    }
}
