//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStatusReasonCategory
    {
        public ProductStatusReasonCategory()
        {
            this.ProductStatusReasonCategoryCultureMap = new HashSet<ProductStatusReasonCategoryCultureMap>();
            this.ProductStatusReasonEntry = new HashSet<ProductStatusReasonEntry>();
            this.ProductStatusReasonLink = new HashSet<ProductStatusReasonLink>();
        }
    
        public int ProductStatusReasonCategoryID { get; set; }
        public string ProductStatusReasonCategoryName { get; set; }
        public string ProductAttributeName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<ProductStatusReasonCategoryCultureMap> ProductStatusReasonCategoryCultureMap { get; set; }
        public virtual ICollection<ProductStatusReasonEntry> ProductStatusReasonEntry { get; set; }
        public virtual ICollection<ProductStatusReasonLink> ProductStatusReasonLink { get; set; }
    }
}
