//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCultureMap
    {
        public ProductCultureMap()
        {
            this.ProductEvent = new HashSet<ProductEvent>();
        }
    
        public int ProductCultureID { get; set; }
        public int ProductID { get; set; }
        public int CultureID { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public decimal BaseUnitPrice { get; set; }
        public Nullable<decimal> ExtraShipFee { get; set; }
        public string ProductName { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public string Keywords { get; set; }
        public bool Activate { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<ProductEvent> ProductEvent { get; set; }
    }
}
