//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueStatus
    {
        public QueueStatus()
        {
            this.AccountMailQueue = new HashSet<AccountMailQueue>();
            this.ProductMailQueue = new HashSet<ProductMailQueue>();
        }
    
        public int QueueStatusID { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<AccountMailQueue> AccountMailQueue { get; set; }
        public virtual ICollection<ProductMailQueue> ProductMailQueue { get; set; }
    }
}
