//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.City = new HashSet<City>();
            this.PostalCode = new HashSet<PostalCode>();
        }
    
        public int RegionID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Region1 { get; set; }
        public string RegionCode { get; set; }
        public string ADM1Code { get; set; }
    
        public virtual ICollection<City> City { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<PostalCode> PostalCode { get; set; }
    }
}
