//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerType
    {
        public SellerType()
        {
            this.Product = new HashSet<Product>();
            this.SellerTypeCultureMap = new HashSet<SellerTypeCultureMap>();
            this.User = new HashSet<User>();
        }
    
        public int SellerTypeID { get; set; }
        public string SellerTypeCodeName { get; set; }
        public string SellerTypeCodeDescription { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<SellerTypeCultureMap> SellerTypeCultureMap { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
