//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerTypeCultureMap
    {
        public int SellerTypeCultureID { get; set; }
        public Nullable<int> SellerTypeID { get; set; }
        public Nullable<int> CultureID { get; set; }
        public string SellerTypeDisplayName { get; set; }
        public string SellerTypeDisplayDescription { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual SellerType SellerType { get; set; }
    }
}
