//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReviewTypeCultureMap
    {
        public int UserReviewTypeCultureID { get; set; }
        public Nullable<int> CultureID { get; set; }
        public Nullable<int> UserReviewTypeID { get; set; }
        public string UserReviewTypeDisplayName { get; set; }
        public string UserReviewTypeDisplayDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual UserReviewType UserReviewType { get; set; }
    }
}
