//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReview
    {
        public UserReview()
        {
            this.UserReviewMap = new HashSet<UserReviewMap>();
        }
    
        public int UserReviewID { get; set; }
        public string ReviewCommentBody { get; set; }
        public Nullable<int> CultureID { get; set; }
        public Nullable<int> ReviewedUserID { get; set; }
        public Nullable<int> ReviewerUserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<UserReviewMap> UserReviewMap { get; set; }
    }
}
