//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReviewType
    {
        public UserReviewType()
        {
            this.UserReviewMap = new HashSet<UserReviewMap>();
            this.UserReviewTypeCultureMap = new HashSet<UserReviewTypeCultureMap>();
        }
    
        public int UserReviewTypeID { get; set; }
        public string UserReviewTypeCodeName { get; set; }
        public Nullable<int> UserReviewTypeWeight { get; set; }
        public Nullable<int> UserReviewDefaultRate { get; set; }
        public Nullable<bool> Activate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<UserReviewMap> UserReviewMap { get; set; }
        public virtual ICollection<UserReviewTypeCultureMap> UserReviewTypeCultureMap { get; set; }
    }
}
