//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AbuseProductReviewMap = new HashSet<AbuseProductReviewMap>();
            this.AttributeEvent = new HashSet<AttributeEvent>();
            this.PageEvent = new HashSet<PageEvent>();
            this.ProductEvent = new HashSet<ProductEvent>();
            this.ProductFavorite = new HashSet<ProductFavorite>();
            this.ProductReview = new HashSet<ProductReview>();
            this.AccountMailQueue = new HashSet<AccountMailQueue>();
            this.PeopleOnline = new HashSet<PeopleOnline>();
            this.PeopleOnlineHistory = new HashSet<PeopleOnlineHistory>();
            this.WhishList = new HashSet<WhishList>();
            this.WhishListEvent = new HashSet<WhishListEvent>();
            this.UserReview = new HashSet<UserReview>();
            this.UserReview1 = new HashSet<UserReview>();
            this.UserRoleMap = new HashSet<UserRoleMap>();
        }
    
        public int UserID { get; set; }
        public Nullable<int> CultureID { get; set; }
        public Nullable<int> EncryptionID { get; set; }
        public int PeopleID { get; set; }
        public int SellerTypeID { get; set; }
        public string EMail { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> TaxExempt { get; set; }
        public Nullable<decimal> GlobalRating { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public Nullable<System.DateTime> LastLockOutDate { get; set; }
        public string PasswordHint { get; set; }
        public string Comment { get; set; }
        public string PasswordAnswer { get; set; }
        public Nullable<int> Locked { get; set; }
        public Nullable<System.DateTime> LockedUntil { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public Nullable<int> FailedAnswerCount { get; set; }
        public bool Activate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<AbuseProductReviewMap> AbuseProductReviewMap { get; set; }
        public virtual ICollection<AttributeEvent> AttributeEvent { get; set; }
        public virtual Culture Culture { get; set; }
        public virtual EncryptionType EncryptionType { get; set; }
        public virtual ICollection<PageEvent> PageEvent { get; set; }
        public virtual People People { get; set; }
        public virtual ICollection<ProductEvent> ProductEvent { get; set; }
        public virtual ICollection<ProductFavorite> ProductFavorite { get; set; }
        public virtual ICollection<ProductReview> ProductReview { get; set; }
        public virtual SellerType SellerType { get; set; }
        public virtual ICollection<AccountMailQueue> AccountMailQueue { get; set; }
        public virtual ICollection<PeopleOnline> PeopleOnline { get; set; }
        public virtual ICollection<PeopleOnlineHistory> PeopleOnlineHistory { get; set; }
        public virtual ICollection<WhishList> WhishList { get; set; }
        public virtual ICollection<WhishListEvent> WhishListEvent { get; set; }
        public virtual ICollection<UserReview> UserReview { get; set; }
        public virtual ICollection<UserReview> UserReview1 { get; set; }
        public virtual ICollection<UserRoleMap> UserRoleMap { get; set; }
    }
}
