//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.RolePermissionMap = new HashSet<RolePermissionMap>();
            this.UserRoleMap = new HashSet<UserRoleMap>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ICollection<RolePermissionMap> RolePermissionMap { get; set; }
        public virtual ICollection<UserRoleMap> UserRoleMap { get; set; }
    }
}
