//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReviewMap
    {
        public int UserReviewMapID { get; set; }
        public Nullable<int> UserReviewID { get; set; }
        public Nullable<int> UserReviewTypeID { get; set; }
        public Nullable<int> UserReviewRate { get; set; }
        public string UserReviewRateComment { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual UserReview UserReview { get; set; }
        public virtual UserReviewType UserReviewType { get; set; }
    }
}
