//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhishListBehavior
    {
        public WhishListBehavior()
        {
            this.WhishListEvent = new HashSet<WhishListEvent>();
        }
    
        public int WhishListBehaviorID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<WhishListEvent> WhishListEvent { get; set; }
    }
}
