//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mendeo.Mercurius.Model.FullDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhishListEvent
    {
        public int WhishListEventID { get; set; }
        public int WhishListBehaviorID { get; set; }
        public Nullable<int> UserID { get; set; }
        public int WhishListID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public System.DateTime EventDate { get; set; }
        public string OldEventContent { get; set; }
        public string EventContent { get; set; }
        public string IP { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual WhishList WhishList { get; set; }
        public virtual WhishListBehavior WhishListBehavior { get; set; }
    }
}
