//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Mendeo.Mercurius.Model.FullDomain.Enum
{
    public enum SellerTypeEnum
    {	
    		NATURAL_PERSON=1,
    LEGAL_ENTITY=2
    	
    }
}
