//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6407
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Maceria.eCommerce.Jobs")]
[assembly: AssemblyDescription("Maceria eCommerce Jobs Layer")]
[assembly: AssemblyCompany("Maceria")]
[assembly: AssemblyProduct("Maceria eCommerce")]
[assembly: AssemblyCopyright("Copyright (c) Maceria, 2009")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]


