//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("IRL.Mvc")]
[assembly: System.Reflection.AssemblyDescription("IRL Mvc")]
[assembly: System.Reflection.AssemblyCompany("SGCIB")]
[assembly: System.Reflection.AssemblyProduct("Irl")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) SGCIB, 2013")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]


