//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Mendeo.Mercurius.Dto")]
[assembly: System.Reflection.AssemblyDescription("Mendeo Library")]
[assembly: System.Reflection.AssemblyCompany("Mendeo")]
[assembly: System.Reflection.AssemblyProduct("Mercurius")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) Mendeo, 2015")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]


