//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRL.Data.AdventureWorks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using IRL.Model.AdventureWorks;
    
    public partial class AdventureWorks2012Entities : DbContext
    {
        public AdventureWorks2012Entities()
            : base("name=AdventureWorks2012Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AWBuildVersion> AWBuildVersion { get; set; }
        public DbSet<DatabaseLog> DatabaseLog { get; set; }
        public DbSet<ErrorLog> ErrorLog { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<EmployeeDepartmentHistory> EmployeeDepartmentHistory { get; set; }
        public DbSet<EmployeePayHistory> EmployeePayHistory { get; set; }
        public DbSet<JobCandidate> JobCandidate { get; set; }
        public DbSet<Shift> Shift { get; set; }
        public DbSet<Address> Address { get; set; }
        public DbSet<AddressType> AddressType { get; set; }
        public DbSet<BusinessEntity> BusinessEntity { get; set; }
        public DbSet<BusinessEntityAddress> BusinessEntityAddress { get; set; }
        public DbSet<BusinessEntityContact> BusinessEntityContact { get; set; }
        public DbSet<ContactType> ContactType { get; set; }
        public DbSet<CountryRegion> CountryRegion { get; set; }
        public DbSet<EmailAddress> EmailAddress { get; set; }
        public DbSet<Password> Password { get; set; }
        public DbSet<Person> Person { get; set; }
        public DbSet<PersonPhone> PersonPhone { get; set; }
        public DbSet<PhoneNumberType> PhoneNumberType { get; set; }
        public DbSet<StateProvince> StateProvince { get; set; }
        public DbSet<BillOfMaterials> BillOfMaterials { get; set; }
        public DbSet<Culture> Culture { get; set; }
        public DbSet<Illustration> Illustration { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductCategory> ProductCategory { get; set; }
        public DbSet<ProductCostHistory> ProductCostHistory { get; set; }
        public DbSet<ProductDescription> ProductDescription { get; set; }
        public DbSet<ProductInventory> ProductInventory { get; set; }
        public DbSet<ProductListPriceHistory> ProductListPriceHistory { get; set; }
        public DbSet<ProductModel> ProductModel { get; set; }
        public DbSet<ProductModelIllustration> ProductModelIllustration { get; set; }
        public DbSet<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCulture { get; set; }
        public DbSet<ProductPhoto> ProductPhoto { get; set; }
        public DbSet<ProductProductPhoto> ProductProductPhoto { get; set; }
        public DbSet<ProductReview> ProductReview { get; set; }
        public DbSet<ProductSubcategory> ProductSubcategory { get; set; }
        public DbSet<ScrapReason> ScrapReason { get; set; }
        public DbSet<TransactionHistory> TransactionHistory { get; set; }
        public DbSet<TransactionHistoryArchive> TransactionHistoryArchive { get; set; }
        public DbSet<UnitMeasure> UnitMeasure { get; set; }
        public DbSet<WorkOrder> WorkOrder { get; set; }
        public DbSet<WorkOrderRouting> WorkOrderRouting { get; set; }
        public DbSet<ProductVendor> ProductVendor { get; set; }
        public DbSet<PurchaseOrderDetail> PurchaseOrderDetail { get; set; }
        public DbSet<PurchaseOrderHeader> PurchaseOrderHeader { get; set; }
        public DbSet<ShipMethod> ShipMethod { get; set; }
        public DbSet<Vendor> Vendor { get; set; }
        public DbSet<CountryRegionCurrency> CountryRegionCurrency { get; set; }
        public DbSet<CreditCard> CreditCard { get; set; }
        public DbSet<Currency> Currency { get; set; }
        public DbSet<CurrencyRate> CurrencyRate { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<PersonCreditCard> PersonCreditCard { get; set; }
        public DbSet<SalesOrderDetail> SalesOrderDetail { get; set; }
        public DbSet<SalesOrderHeader> SalesOrderHeader { get; set; }
        public DbSet<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReason { get; set; }
        public DbSet<SalesPerson> SalesPerson { get; set; }
        public DbSet<SalesPersonQuotaHistory> SalesPersonQuotaHistory { get; set; }
        public DbSet<SalesReason> SalesReason { get; set; }
        public DbSet<SalesTaxRate> SalesTaxRate { get; set; }
        public DbSet<SalesTerritory> SalesTerritory { get; set; }
        public DbSet<SalesTerritoryHistory> SalesTerritoryHistory { get; set; }
        public DbSet<ShoppingCartItem> ShoppingCartItem { get; set; }
        public DbSet<SpecialOffer> SpecialOffer { get; set; }
        public DbSet<SpecialOfferProduct> SpecialOfferProduct { get; set; }
        public DbSet<Store> Store { get; set; }
        public DbSet<vEmployee> vEmployee { get; set; }
        public DbSet<vEmployeeDepartment> vEmployeeDepartment { get; set; }
        public DbSet<vEmployeeDepartmentHistory> vEmployeeDepartmentHistory { get; set; }
        public DbSet<vJobCandidate> vJobCandidate { get; set; }
        public DbSet<vJobCandidateEducation> vJobCandidateEducation { get; set; }
        public DbSet<vJobCandidateEmployment> vJobCandidateEmployment { get; set; }
        public DbSet<vAdditionalContactInfo> vAdditionalContactInfo { get; set; }
        public DbSet<vStateProvinceCountryRegion> vStateProvinceCountryRegion { get; set; }
        public DbSet<vProductAndDescription> vProductAndDescription { get; set; }
        public DbSet<vProductModelCatalogDescription> vProductModelCatalogDescription { get; set; }
        public DbSet<vProductModelInstructions> vProductModelInstructions { get; set; }
        public DbSet<vVendorWithAddresses> vVendorWithAddresses { get; set; }
        public DbSet<vVendorWithContacts> vVendorWithContacts { get; set; }
        public DbSet<vIndividualCustomer> vIndividualCustomer { get; set; }
        public DbSet<vPersonDemographics> vPersonDemographics { get; set; }
        public DbSet<vSalesPerson> vSalesPerson { get; set; }
        public DbSet<vSalesPersonSalesByFiscalYears> vSalesPersonSalesByFiscalYears { get; set; }
        public DbSet<vStoreWithAddresses> vStoreWithAddresses { get; set; }
        public DbSet<vStoreWithContacts> vStoreWithContacts { get; set; }
        public DbSet<vStoreWithDemographics> vStoreWithDemographics { get; set; }
    }
}
